import Route from 'ember-route';

export default Route.extend({
  model() {
    return {
      svg: [
        {svgID: "#svg-folder"},
        {svgID: "#svg-folder-fill"},
        {svgID: "#arrows-16px-1_download"},
        {svgID: "#arrows-16px-1_fullscreen-double-74"},
        {svgID: "#arrows-16px-1_log-out"},
        {svgID: "#arrows-16px-1_minimal-down"},
        {svgID: "#arrows-16px-1_share-91"},
        {svgID: "#arrows-16px-1_shuffle-98"},
        {svgID: "#arrows-16px-1_small-triangle-down"},
        {svgID: "#arrows-16px-2_select-84"},
        {svgID: "#arrows-16px-2_small-right"},
        {svgID: "#arrows-16px-3_small-down"},
        {svgID: "#arrows-16px-4_logout"},
        {svgID: "#arrows-16px-4_redo-10"},
        {svgID: "#arrows-16px-4_split-37"},
        {svgID: "#arrows-16px-4_stre-down"},
        {svgID: "#arrows-16px-4_stre-right"},
        {svgID: "#arrows-16px-e_refresh-19"},
        {svgID: "#arrows-16px-e_refresh-20"},
        {svgID: "#arrows-16px-e_share-26"},
        {svgID: "#business-16px_chart-bar-32"},
        {svgID: "#business-16px_chart-pie-36"},
        {svgID: "#business-16px_connect"},
        {svgID: "#business-16px_currency-yen"},
        {svgID: "#business-16px_hierarchy-53"},
        {svgID: "#business-16px_math"},
        {svgID: "#business-16px_notes"},
        {svgID: "#business-16px_plug"},
        {svgID: "#business-16px_sign"},
        {svgID: "#clothes-16px_glasses"},
        {svgID: "#design-16px-2_3d-29"},
        {svgID: "#design-16px-2_filter-organization"},
        {svgID: "#design-16px-2_layers"},
        {svgID: "#design-16px-2_ungroup"},
        {svgID: "#design-16px_mouse-08"},
        {svgID: "#design-16px_path-unite"},
        {svgID: "#design-16px_pen-01"},
        {svgID: "#design-16px_wand-11"},
        {svgID: "#education-16px_award-55"},
        {svgID: "#envir-16px_waste-recycling"},
        {svgID: "#files-16px-e_add"},
        {svgID: "#files-16px-e_folder-03"},
        {svgID: "#files-16px-e_folder-add"},
        {svgID: "#files-16px-e_folder-remove"},
        {svgID: "#files-16px-e_remove"},
        {svgID: "#files-16px_folder-15"},
        {svgID: "#files-16px_single-content-03"},
        {svgID: "#files-16px_single-copy-04"},
        {svgID: "#files-16px_single-copy-06"},
        {svgID: "#files-16px_single-folded"},
        {svgID: "#files-16px_single-folded-content"},
        {svgID: "#health-16px_pulse"},
        {svgID: "#holidays-16px_gift"},
        {svgID: "#media-16px-1_button-power"},
        {svgID: "#media-16px-1_image-02"},
        {svgID: "#media-16px-1_video-65"},
        {svgID: "#objects-16px_spaceship"},
        {svgID: "#ui-16px-1_bell-53"},
        {svgID: "#ui-16px-1_pencil"},
        {svgID: "#ui-16px-1_trash"},
        {svgID: "#ui-16px-2_favourite-31"},
        {svgID: "#ui-16px-2_time-clock"},
        {svgID: "#users-16px_single-body"},
      ]
    };
  }
});
