import Route from 'ember-route';

export default Route.extend({
  model() {
    return {
      svg: [
        {icon: "brush"},
        {icon: "arrows-small-triangle-down"},
        {icon: "arrows-select"},
        {icon: "arrows-small-right"},
        {icon: "arrows-small-down"},
        {icon: "design-pen"},
        {icon: "education-award"},
        {icon: "education-glasses"},
        {icon: "files-folder"},
        {icon: "files-folder-add"},
        {icon: "files-folder-remove"},
        {icon: "files-folder"},
        {icon: "files-single-copy"},
        {icon: "files-single-folded"},
        {icon: "files-single-folded-content"},
        {icon: "gestures-scan"},
        {icon: "media-button-power"},
        {icon: "media-image"},
        {icon: "media-play"},
        {icon: "shopping-bardcode-qr"},
        {icon: "shopping-cart"},
        {icon: "ui-bell"},
        {icon: "ui-check"},
        {icon: "ui-check-simple"},
        {icon: "ui-check-small"},
        {icon: "ui-email"},
        {icon: "ui-notification"},
        {icon: "ui-pencil"},
        {icon: "ui-preferences-circle"},
        {icon: "ui-settings-gear"},
        {icon: "ui-simple-add"},
        {icon: "ui-simple-delete"},
        {icon: "ui-simple-remove"},
        {icon: "ui-zoom"},
        {icon: "ui-alert-?"},
        {icon: "ui-alert-circle-?"},
        {icon: "ui-alert-i"},
        {icon: "ui-grid-1"},
        {icon: "ui-grid-2"},
        {icon: "ui-grid-square"},
        {icon: "ui-link"},
        {icon: "ui-share"},
        {icon: "ui-small-add"},
        {icon: "ui-small-delete"},
        {icon: "ui-small-remove"},
        {icon: "ui-time-clock"},
        {icon: "ui-alert"},
        {icon: "ui-infinite"},
        {icon: "ui-round-e-help"},
        {icon: "ui-round-e-info"},
        {icon: "ui-square-e-info"},
      ]
    };
  }
});
